# Generated by Django 6.0.2 on 2026-03-31 06:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HclsWebApi', '0011_passwordresettoken_alter_checklogin_admin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogin',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='Createdby',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checklogin',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='CreatedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admins', to='HclsWebApi.checklogin'),
        ),
        migrations.AddField(
            model_name='checklogin',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedOn', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
