# Generated by Django 6.0.2 on 2026-03-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HclsWebApi', '0012_adminlogin_createdon_adminlogin_createdby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklogin',
            name='address',
            field=models.CharField(blank=True, db_column='Address', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checklogin',
            name='gender',
            field=models.CharField(blank=True, db_column='Gender', max_length=10, null=True),
        ),
    ]
