# Generated by Django 6.0.2 on 2026-03-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HclsWebApi', '0013_checklogin_address_checklogin_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklogin',
            name='avatar',
            field=models.ImageField(blank=True, db_column='Avatar', null=True, upload_to='avatars/'),
        ),
    ]
