# Generated by Django 6.0.2 on 2026-04-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HclsWebApi', '0014_checklogin_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlogin',
            name='CreatedOn',
        ),
        migrations.RemoveField(
            model_name='adminlogin',
            name='Createdby',
        ),
    ]
